name: WebstoreIntegration
version: 1.1.0
main: me.millosaurs.webstoreApi.WebstoreIntegrationPlugin
api-version: 1.20
author: Millosaurs
description: Enhanced Minecraft webstore integration plugin with offline delivery
website: https://github.com/Millosaurs/Mc-webstore

# Plugin will work better with these plugins installed
softdepend:
  - LuckPerms
  - Vault

# Commands (optional - for future use)
commands:
  webstore:
    description: Webstore integration commands
    usage: /webstore <reload|status>
    permission: webstore.admin

# Permissions (optional - for future use)
permissions:
  webstore.admin:
    description: Access to webstore admin commands
    default: op